# Generated by Django 2.1.2 on 2018-10-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_articles_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
